
export { ReactComponent as Moon } from "./Icon-Moon.svg"
export { ReactComponent as Sun } from "./Icon-Sun.svg"
export { ReactComponent as Logo } from "./logo.svg"
export { ReactComponent as IconDarkMode } from "./Icon-DarkMode.svg"
export { ReactComponent as IconLogin } from "./Icon-Login.svg"
export { ReactComponent as IconAddUser } from "./Icon-Add-User.svg"
export { ReactComponent as IconSettings } from "./Icon-Settings.svg"
export { ReactComponent as IconLogOut } from "./Icon-LogOut.svg"
export { ReactComponent as IconBurger } from "./Icon-Burger.svg"
export { ReactComponent as IconClose } from "./Icon-X.svg"
export { ReactComponent as IconGrid } from "./Icon-Grid.svg"
export { ReactComponent as IconList } from "./Icon-List.svg"
